import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { getTemplate } from '../features/templates/templateCatalog';

type PreviewPage = 'Home' | 'About' | 'Academics' | 'Admissions' | 'Campus life' | 'News' | 'Contact';
type SavedTemplateSettings = { accent?: string; accentSoft?: string; font?: string; variant?: string; motion?: string; title?: string; text?: string };

const pageContent: Record<Exclude<PreviewPage, 'Home'>, { eyebrow: string; title: string; copy: string; feature: string; cards: string[] }> = {
  About: { eyebrow: 'Our story', title: 'A community where every child is known.', copy: 'We create an environment where children feel safe to be curious, make meaningful connections and discover what they can do.', feature: 'Built on shared values', cards: ['Our purpose', 'Leadership team', 'Our values'] },
  Academics: { eyebrow: 'Learning pathways', title: 'Ambitious learning, shaped around each child.', copy: 'From early exploration to confident next steps, our teaching helps learners build knowledge, creativity and independence.', feature: 'A curriculum with depth', cards: ['Early years', 'Junior school', 'Senior school'] },
  Admissions: { eyebrow: 'Join our community', title: 'Your child’s next chapter starts here.', copy: 'Choosing a school is a big decision. Our friendly admissions team is ready to show you our campus and answer every question.', feature: 'A simple admissions journey', cards: ['Book a visit', 'Apply online', 'Meet the team'] },
  'Campus life': { eyebrow: 'Life beyond the classroom', title: 'Every day brings a new opportunity to belong.', copy: 'Sport, music, creativity, service and friendship are all part of a rich school experience that develops confident young people.', feature: 'Make the most of school life', cards: ['Arts & culture', 'Sport & wellbeing', 'Clubs & leadership'] },
  News: { eyebrow: 'Stories from our school', title: 'See what is happening in our community.', copy: 'Explore the moments, achievements and ideas that make life at our school so special.', feature: 'Latest news & events', cards: ['Young innovators shine at science fair', 'Open morning: meet our teachers', 'Community action day'] },
  Contact: { eyebrow: 'Get in touch', title: 'Come and see our school for yourself.', copy: 'We would love to welcome you to campus, introduce you to our team and help you understand what makes our community different.', feature: 'Visit & connect', cards: ['Plan your visit', 'Contact admissions', 'Find our campus'] },
};

function LandingHero({ template, title, text }: { template: ReturnType<typeof getTemplate>; title?: string; text?: string }) {
  const button = <button className="mt-7 px-5 py-3 text-sm font-bold text-white" style={{ background: template.accent }}>Explore our school</button>;
  if (template.layout === 'classic') return <section className="bg-[#fffaf2] px-6 py-16 text-center sm:px-12 lg:px-20"><div className="mx-auto max-w-4xl border-y-2 py-10" style={{ borderColor: template.accent }}><p className="text-xs font-bold uppercase tracking-[.25em]" style={{ color: template.accent }}>Welcome to your school</p><h1 className="mx-auto mt-5 max-w-3xl text-5xl font-semibold leading-tight" style={{ color: template.dark }}>A wonderful place to learn, grow and belong.</h1><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-slate-600">A caring community with a rich tradition of helping every child find their path.</p>{button}</div><div className="mx-auto mt-10 grid max-w-5xl gap-4 md:grid-cols-3">{['A tradition of care', 'Inspired teaching', 'A joyful community'].map((item) => <div key={item} className="border p-6 text-left" style={{ borderColor: template.accentSoft }}><div className="h-20" style={{ background: template.accentSoft }}/><p className="mt-4 font-semibold" style={{ color: template.dark }}>{item}</p></div>)}</div></section>;
  if (template.layout === 'playful') return <section className="relative overflow-hidden bg-orange-50 px-6 py-16 sm:px-12 lg:px-20"><div className="absolute -left-10 -top-10 h-48 w-48 rounded-full" style={{ background: template.accentSoft }}/><div className="relative mx-auto max-w-4xl text-center"><span className="inline-block rotate-[-2deg] rounded-full px-4 py-2 text-xs font-bold text-white" style={{ background: template.accent }}>Play · learn · shine</span><h1 className="mt-6 text-5xl font-black leading-[.98]" style={{ color: template.dark }}>Big adventures start with little learners.</h1><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-slate-600">A happy, colourful school experience where every day brings something new to discover.</p>{button}</div><div className="relative mx-auto mt-12 grid max-w-5xl grid-cols-2 gap-4 md:grid-cols-4">{['Create', 'Explore', 'Move', 'Imagine'].map((item, index) => <div key={item} className={`rounded-3xl p-6 ${index % 2 ? 'translate-y-5' : ''}`} style={{ background: [template.accentSoft, '#fde68a', '#bfdbfe', '#bbf7d0'][index] }}><div className="h-10 w-10 rounded-full bg-white/70"/><p className="mt-8 font-bold" style={{ color: template.dark }}>{item}</p></div>)}</div></section>;
  if (template.layout === 'minimal') return <section className="px-6 py-20 sm:px-12 lg:px-20"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><p className="text-xs font-bold uppercase tracking-[.25em]" style={{ color: template.accent }}>Independent learning</p><div><h1 className="text-5xl font-semibold leading-[1.03]" style={{ color: template.dark }}>Space to think. Time to become.</h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-500">A focused education for thoughtful young people, built around deep learning and real connection.</p>{button}</div></div><div className="mx-auto mt-16 grid max-w-6xl gap-5 md:grid-cols-[1.5fr_.5fr_.5fr]"><div className="h-80 bg-slate-100"/><div className="h-80" style={{ background: template.dark }}/><div className="h-80" style={{ background: template.accentSoft }}/></div></section>;
  if (template.layout === 'heritage') return <section className="bg-[#fffdf7] px-6 py-16 sm:px-12 lg:px-20"><div className="mx-auto max-w-6xl rounded-[2rem] p-8 text-center sm:p-16" style={{ background: template.accentSoft }}><div className="mx-auto h-14 w-14 rotate-45 border-4 bg-white" style={{ borderColor: template.accent }}/><p className="mt-7 text-xs font-bold uppercase tracking-[.25em]" style={{ color: template.accent }}>A school with heart</p><h1 className="mx-auto mt-5 max-w-3xl text-5xl font-semibold leading-tight" style={{ color: template.dark }}>Honouring tradition. Preparing for tomorrow.</h1><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-slate-600">A welcoming school community shaped by character, scholarship and a sense of belonging.</p>{button}</div></section>;
  if (template.layout === 'stem') return <section className="bg-sky-50 px-6 py-12 sm:px-12 lg:px-20"><div className="mx-auto grid max-w-6xl gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl p-9" style={{ background: template.dark }}><p className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: template.accentSoft }}>Future-ready learning</p><h1 className="mt-5 text-5xl font-semibold leading-[1.03] text-white">{title ?? 'Think boldly. Build what is next.'}</h1><p className="mt-6 max-w-lg text-base leading-7 text-white/70">{text ?? 'A practical, creative education for problem solvers, makers and future leaders.'}</p>{button}</div><div className="grid grid-cols-3 gap-3">{Array.from({ length: 9 }, (_, index) => <div key={index} className={`min-h-24 rounded-2xl ${index === 1 || index === 6 ? 'col-span-2' : ''}`} style={{ background: index === 1 || index === 6 ? template.accent : index % 2 ? '#dbeafe' : '#e0f2fe' }} />)}</div></div></section>;
  return <section className="grid gap-8 px-6 py-16 sm:px-12 lg:grid-cols-[1.1fr_.9fr] lg:px-20 lg:py-24" style={{ background: template.dark }}><div><p className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: template.accentSoft }}>A place to grow</p><h1 className="mt-5 max-w-2xl text-5xl font-semibold leading-[1.03] text-white sm:text-6xl">{title ?? 'Learning that lets every child thrive.'}</h1><p className="mt-6 max-w-xl text-base leading-7 text-white/70">{text ?? 'A welcoming, ambitious school community for curious young people who are ready to discover their potential.'}</p>{button}</div><div className="min-h-72 rounded-2xl p-6" style={{ background: `linear-gradient(145deg, ${template.accent}, ${template.accentSoft})` }}><div className="ml-auto h-28 w-28 rounded-full border-[18px] border-white/65"/><div className="mt-40 h-4 w-44 rounded bg-white/70"/></div></section>;
}

export default function TemplateLivePreviewPage() {
  const { templateId } = useParams();
  const baseTemplate = getTemplate(templateId);
  const [savedSettings] = useState(() => {
    try {
      return JSON.parse(localStorage.getItem(`school-template:${baseTemplate.id}`) ?? '{}') as SavedTemplateSettings;
    } catch {
      return {};
    }
  });
  const template = { ...baseTemplate, ...savedSettings };
  const [page, setPage] = useState<PreviewPage>('Home');
  // The Home view does not use this value; the fallback keeps the detail
  // page markup fully typed for the other six website pages.
  const detail = pageContent[page === 'Home' ? 'About' : page];

  return (
    <div className="min-h-screen bg-white" style={{ fontFamily: template.font }}>
      <header className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white/95 px-5 py-4 backdrop-blur sm:px-10"><div className="flex items-center gap-4"><Link to="/schooladmin/website/templates" className="rounded-md border border-slate-200 px-3 py-2 text-xs font-bold text-slate-500 transition hover:border-slate-400 hover:text-slate-900">Exit preview</Link><button onClick={() => setPage('Home')} className="text-lg font-bold tracking-tight" style={{ color: template.dark }}>YOUR <span style={{ color: template.accent }}>SCHOOL</span></button></div><nav className="hidden items-center gap-5 lg:flex">{(['Home', 'About', 'Academics', 'Admissions', 'Campus life', 'News', 'Contact'] as PreviewPage[]).map((item) => <button key={item} onClick={() => { setPage(item); window.scrollTo({ top: 0, behavior: 'smooth' }); }} className={`text-xs font-semibold transition ${page === item ? 'text-slate-900' : 'text-slate-500 hover:text-slate-900'}`} style={page === item ? { color: template.accent } : undefined}>{item}</button>)}</nav><button className="rounded-md px-3 py-2 text-xs font-bold text-white" style={{ background: template.accent }}>Enquire now</button></header>

      {page === 'Home' ? <>
        <LandingHero template={template} title={savedSettings.title} text={savedSettings.text} />
        <section className="grid grid-cols-1 divide-y divide-slate-100 border-b border-slate-100 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div className="px-8 py-8 text-center"><p className="text-3xl font-bold" style={{ color: template.accent }}>98%</p><p className="mt-1 text-sm text-slate-500">Progression rate</p></div><div className="px-8 py-8 text-center"><p className="text-3xl font-bold" style={{ color: template.accent }}>24</p><p className="mt-1 text-sm text-slate-500">Clubs & societies</p></div><div className="px-8 py-8 text-center"><p className="text-3xl font-bold" style={{ color: template.accent }}>1:12</p><p className="mt-1 text-sm text-slate-500">Teacher ratio</p></div></section>
        <section className="px-6 py-20 sm:px-12 lg:px-20"><p className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: template.accent }}>Learning pathways</p><div className="mt-4 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="max-w-xl text-4xl font-semibold leading-tight" style={{ color: template.dark }}>An education that grows with every learner.</h2><button onClick={() => setPage('Academics')} className="text-sm font-bold" style={{ color: template.accent }}>Explore academics →</button></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[['01', 'Early years', 'Play, explore and belong.'], ['02', 'Junior school', 'Curiosity turns into confidence.'], ['03', 'Senior school', 'Ready for the world beyond.']].map(([number, heading, copy]) => <article key={heading} className="rounded-2xl border border-slate-100 p-6 shadow-sm"><span className="text-sm font-bold" style={{ color: template.accent }}>{number}</span><div className="mt-8 h-36 rounded-xl bg-slate-100"/><h3 className="mt-5 text-xl font-semibold" style={{ color: template.dark }}>{heading}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{copy}</p></article>)}</div></section>
        <section className="grid gap-10 px-6 py-20 sm:px-12 lg:grid-cols-2 lg:px-20" style={{ background: template.accentSoft }}><div className="min-h-80 rounded-2xl" style={{ background: `linear-gradient(135deg, ${template.dark}, ${template.accent})` }}/><div className="self-center"><p className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: template.accent }}>Our community</p><h2 className="mt-4 text-4xl font-semibold leading-tight" style={{ color: template.dark }}>A campus made for discovery.</h2><p className="mt-5 max-w-lg text-base leading-7 text-slate-600">Beautiful spaces, generous ideas and a school community where every learner is encouraged to find their voice.</p><button onClick={() => setPage('Campus life')} className="mt-7 text-sm font-bold" style={{ color: template.accent }}>Meet our community →</button></div></section>
        <section className="px-6 py-20 sm:px-12 lg:px-20"><p className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: template.accent }}>From the school</p><h2 className="mt-4 text-4xl font-semibold" style={{ color: template.dark }}>Latest stories and events</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{['Young innovators shine at science fair', 'Open morning: meet our teachers', 'Community action day'].map((story) => <article key={story} className="rounded-2xl border border-slate-100 p-5"><div className="h-40 rounded-xl bg-slate-100"/><p className="mt-5 text-xs font-bold uppercase tracking-wide" style={{ color: template.accent }}>School news</p><h3 className="mt-2 text-lg font-semibold leading-6" style={{ color: template.dark }}>{story}</h3><button onClick={() => setPage('News')} className="mt-5 text-xs font-bold" style={{ color: template.accent }}>Read story →</button></article>)}</div></section>
      </> : <>
        <section className="px-6 py-20 text-center sm:px-12 lg:px-20" style={{ background: template.accentSoft }}><p className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: template.accent }}>{detail.eyebrow}</p><h1 className="mx-auto mt-5 max-w-3xl text-5xl font-semibold leading-tight" style={{ color: template.dark }}>{detail.title}</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-600">{detail.copy}</p><button className="mt-8 rounded-md px-5 py-3 text-sm font-bold text-white" style={{ background: template.accent }}>Arrange a visit</button></section>
        <section className="grid gap-12 px-6 py-20 sm:px-12 lg:grid-cols-[.9fr_1.1fr] lg:px-20"><div className="min-h-80 rounded-2xl" style={{ background: `linear-gradient(145deg, ${template.dark}, ${template.accent})` }}/><div className="self-center"><p className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: template.accent }}>{detail.feature}</p><h2 className="mt-4 text-4xl font-semibold leading-tight" style={{ color: template.dark }}>Designed to help every learner flourish.</h2><p className="mt-5 text-base leading-7 text-slate-500">Thoughtful experiences, inspiring spaces and a strong partnership with families create a community where young people can do their best work.</p></div></section>
        <section className="px-6 py-20 sm:px-12 lg:px-20" style={{ background: '#f8fafc' }}><div className="grid gap-5 md:grid-cols-3">{detail.cards.map((card, index) => <article key={card} className="rounded-2xl bg-white p-7 shadow-sm"><span className="text-sm font-bold" style={{ color: template.accent }}>0{index + 1}</span><h3 className="mt-8 text-xl font-semibold" style={{ color: template.dark }}>{card}</h3><p className="mt-3 text-sm leading-6 text-slate-500">Find out more about this part of our school community and how to get involved.</p><button className="mt-6 text-sm font-bold" style={{ color: template.accent }}>Learn more →</button></article>)}</div></section>
      </>}
      <footer className="px-6 py-12 text-white sm:px-12 lg:px-20" style={{ background: template.dark }}><div className="flex flex-col justify-between gap-8 md:flex-row"><div><p className="text-xl font-bold">YOUR SCHOOL</p><p className="mt-3 max-w-xs text-sm leading-6 text-white/60">Inspiring young people to learn, contribute and thrive.</p></div><div className="grid grid-cols-3 gap-10 text-sm text-white/65"><div>About<br/><span className="leading-8">Our story<br/>Leadership</span></div><div>Learning<br/><span className="leading-8">Programmes<br/>Admissions</span></div><div>Connect<br/><span className="leading-8">Visit us<br/>Contact</span></div></div></div><div className="mt-10 border-t border-white/10 pt-5 text-xs text-white/40">© Your School · Website preview</div></footer>
    </div>
  );
}
